In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [ ]:
import cv2

In [ ]:
filepath_mat="/content/gdrive/MyDrive/Adv-original/test_set/sample_0_African_hunting_dog_orig.mat"
filepath_png="/content/gdrive/MyDrive/Adv-original/dataset/Dataset/Training/orig/sample_0_African_hunting_dog_orig..png"
outpath="/content/gdrive/MyDrive/Adv-original/dataset/test_set"

In [ ]:
 mat_contents = sio.loadmat(filepath_mat)

In [ ]:
img=np.array((mat_contents['orig']*255).astype('uint8'))

In [ ]:
img

array([[[210, 173, 131],
        [209, 172, 130],
        [210, 171, 130],
        ...,
        [226, 196, 162],
        [224, 194, 158],
        [225, 195, 159]],

       [[210, 173, 131],
        [209, 172, 130],
        [209, 170, 129],
        ...,
        [228, 198, 164],
        [227, 197, 161],
        [226, 196, 160]],

       [[211, 174, 132],
        [207, 170, 126],
        [209, 170, 127],
        ...,
        [225, 195, 161],
        [224, 194, 158],
        [223, 193, 157]],

       ...,

       [[232, 214, 190],
        [224, 207, 187],
        [224, 202, 181],
        ...,
        [193, 129,  81],
        [164, 135,  91],
        [172, 151,  86]],

       [[196, 204, 121],
        [174, 152, 141],
        [191, 171, 164],
        ...,
        [221, 207, 196],
        [208, 188, 155],
        [163, 146,  94]],

       [[121, 130,  37],
        [255, 244, 231],
        [164, 145, 139],
        ...,
        [233, 196, 177],
        [206, 174, 149],
        [177, 158, 118]]

In [ ]:
png = cv2.imread(filepath_png)

In [ ]:
png

array([[[131, 173, 210],
        [130, 172, 209],
        [130, 171, 210],
        ...,
        [162, 196, 226],
        [158, 194, 224],
        [159, 195, 225]],

       [[131, 173, 210],
        [130, 172, 209],
        [129, 170, 209],
        ...,
        [164, 198, 228],
        [161, 197, 227],
        [160, 196, 226]],

       [[132, 174, 211],
        [126, 170, 207],
        [127, 170, 209],
        ...,
        [161, 195, 225],
        [158, 194, 224],
        [157, 193, 223]],

       ...,

       [[190, 214, 232],
        [187, 207, 224],
        [181, 202, 224],
        ...,
        [ 81, 129, 193],
        [ 91, 135, 164],
        [ 86, 151, 172]],

       [[121, 204, 196],
        [141, 152, 174],
        [164, 171, 191],
        ...,
        [196, 207, 221],
        [155, 188, 208],
        [ 94, 146, 163]],

       [[ 37, 130, 121],
        [231, 244, 255],
        [139, 145, 164],
        ...,
        [177, 196, 233],
        [149, 174, 206],
        [118, 158, 177]]

In [ ]:
img - png

array([[[ 79,   0, 177],
        [ 79,   0, 177],
        [ 80,   0, 176],
        ...,
        [ 64,   0, 192],
        [ 66,   0, 190],
        [ 66,   0, 190]],

       [[ 79,   0, 177],
        [ 79,   0, 177],
        [ 80,   0, 176],
        ...,
        [ 64,   0, 192],
        [ 66,   0, 190],
        [ 66,   0, 190]],

       [[ 79,   0, 177],
        [ 81,   0, 175],
        [ 82,   0, 174],
        ...,
        [ 64,   0, 192],
        [ 66,   0, 190],
        [ 66,   0, 190]],

       ...,

       [[ 42,   0, 214],
        [ 37,   0, 219],
        [ 43,   0, 213],
        ...,
        [112,   0, 144],
        [ 73,   0, 183],
        [ 86,   0, 170]],

       [[ 75,   0, 181],
        [ 33,   0, 223],
        [ 27,   0, 229],
        ...,
        [ 25,   0, 231],
        [ 53,   0, 203],
        [ 69,   0, 187]],

       [[ 84,   0, 172],
        [ 24,   0, 232],
        [ 25,   0, 231],
        ...,
        [ 56,   0, 200],
        [ 57,   0, 199],
        [ 59,   0, 197]]

In [ ]:
import numpy as np
import os
from PIL import Image
import scipy.io as sio

In [ ]:
i=0
for filename in os.listdir(filepath):
  mat_contents = sio.loadmat(filepath+'/'+filename)
  if 'orig' in mat_contents:
    img=np.array((mat_contents['orig']*255).astype('uint8'))
  else:
    img=np.array((mat_contents['adv']*255).astype('uint8'))
  im = Image.fromarray(img)
  im.save(outpath+'/'+filename[:-3]+".png")
  i=i+1
print(i)

FileNotFoundError: ignored